[package]
name = "axum_routes_macro"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
ctor = "0.1"

[lib]
proc-macro = true
